require 'bundler'
require 'bundler/gem_tasks'
require 'geminabox'
require 'rake'
require 'rake/clean'
CLEAN.include('pkg')

task :default => 'opentpx:spec'

namespace:opentpx do
  require 'bundler'
  require 'rake'
  require 'rspec/core/rake_task'

  desc 'Run specs marked with the supplied tag.'
  RSpec::Core::RakeTask.new(:spec, :tag) do |t, task_args|
    if task_args.has_key?(:tag)
      t.rspec_opts = "-fd --tag #{task_args[:tag]}"
    else
      t.rspec_opts = "-fd"
    end
  end
end
